# Generated by Django 3.2.2 on 2021-05-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0004_auto_20210512_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Certificate_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ourapp.certificate_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ourapp.school'),
        ),
    ]
