# Generated by Django 3.2.2 on 2021-05-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0007_auto_20210512_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ourapp.department'),
            preserve_default=False,
        ),
    ]
