# Generated by Django 3.2.2 on 2021-05-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0008_auto_20210512_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Department',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='ourapp.department'),
            preserve_default=False,
        ),
    ]
