# Generated by Django 3.2.2 on 2021-05-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0009_auto_20210512_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
