# Generated by Django 3.2.2 on 2021-05-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0011_student_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year_of_graduation',
            new_name='graduation_date',
        ),
    ]
